SELECT * FROM FABRICANTE;

SELECT * FROM FABRICANTE WHERE CODIGO = 3;
SELECT NOMBRE FROM FABRICANTE WHERE CODIGO = 5;
SELECT CODIGO, NOMBRE FROM FABRICANTE WHERE CODIGO = 5;
SELECT * FROM FABRICANTE WHERE CODIGO = 5;
SELECT * FROM FABRICANTE WHERE CODIGO < 7;
SELECT * FROM FABRICANTE WHERE CODIGO > 7;
SELECT * FROM FABRICANTE WHERE NOMBRE = 'LENOVO'; /*NO DISTINGUE MAYUS O MIN*/
SELECT COUNT(*) FROM FABRICANTE;
SELECT COUNT(*) FROM FABRICANTE WHERE NOMBRE = 'LENOVO';
SELECT MAX(CODIGO) FROM FABRICANTE;
SELECT MIN(CODIGO) FROM FABRICANTE;
SELECT * FROM FABRICANTE WHERE CODIGO IN (3,5);
SELECT * FROM FABRICANTE WHERE NOMBRE LIKE '%su%';
SELECT * FROM FABRICANTE WHERE NOMBRE LIKE 'sus%';
SELECT * FROM FABRICANTE WHERE NOMBRE LIKE ('%sus');
SELECT * FROM FABRICANTE WHERE CODIGO BETWEEN 2 AND 7;

SELECT * FROM PRODUCTO;

/*EJEMPLOS DE CONSULTAS*/

/*VINCULAR AMBAS TABLAS*/
SELECT f.nombre, p.nombre, p.precio
	FROM FABRICANTE F, PRODUCTO P 
WHERE F.CODIGO = P.CODIGO_FABRICANTE;

/*código del fabricante = 7*/
SELECT f.nombre, p.nombre, p.precio
	FROM FABRICANTE F, PRODUCTO P 
WHERE F.CODIGO = P.CODIGO_FABRICANTE
	AND F.CODIGO = 7;
    
/*Solo nombre y código del fabricante que el código sea igual a 7*/
SELECT f.nombre, f.codigo
	FROM FABRICANTE F, PRODUCTO P 
WHERE F.CODIGO = P.CODIGO_FABRICANTE
	AND F.CODIGO = 7;

/*Todos los valores de la tabla producto pero para el fabricanre del codigo 7*/
SELECT p.codigo, p.nombre, p.precio
	FROM FABRICANTE F, PRODUCTO P 
WHERE F.CODIGO = P.CODIGO_FABRICANTE
	AND F.CODIGO = 7;  
    
/*Todos los valores de la tabla producto pero para el fabricante
de nombre lenovo*/
SELECT p.codigo, p.nombre, p.precio
	FROM FABRICANTE F, PRODUCTO P 
WHERE F.CODIGO = P.CODIGO_FABRICANTE
	AND F.nombre = 'lenovo';  
    
/*Todos los valores de la tabla producto pero para el fabricante
de nombre lenovo y su precio sea mayor de 450*/
SELECT p.codigo, p.nombre, p.precio
	FROM FABRICANTE F, PRODUCTO P 
WHERE F.CODIGO = P.CODIGO_FABRICANTE
	AND F.nombre = 'lenovo'
    AND P.PRECIO > 450;
